### ISSUE TITLE
vgcal init時にmkdir_pメソッドの引数でエラーが発生する

### ISSUE THREAD

**Issue by st1t** [st1t/vgcal#4]
```
$ vgcal init
/Users/ito.shota/.rbenv/versions/3.1.2/lib/ruby/3.1.0/fileutils.rb:206:in `mkdir_p': wrong number of arguments (given 2, expected 1) (ArgumentError)
	from /Users/ito.shota/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/vgcal-0.4.3/lib/vgcal/handlers/describer.rb:19:in `init'
	from /Users/ito.shota/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /Users/ito.shota/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/ito.shota/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /Users/ito.shota/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from /Users/ito.shota/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/vgcal-0.4.3/lib/vgcal/handlers/describer.rb:167:in `<top (required)>'
	from <internal:/Users/ito.shota/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/ito.shota/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/ito.shota/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/vgcal-0.4.3/lib/vgcal.rb:8:in `<module:Vgcal>'
	from /Users/ito.shota/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/vgcal-0.4.3/lib/vgcal.rb:6:in `<top (required)>'
	from <internal:/Users/ito.shota/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/ito.shota/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/ito.shota/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/vgcal-0.4.3/exe/vgcal:3:in `<top (required)>'
	from /Users/ito.shota/.rbenv/versions/3.1.2/bin/vgcal:25:in `load'
	from /Users/ito.shota/.rbenv/versions/3.1.2/bin/vgcal:25:in `<main>'
$ 
```

**Comment by st1t** [comment]
https://github.com/st1t/vgcal/blob/master/lib/vgcal/handlers/describer.rb#L19 のmodeの指定ミス。

```
FileUtils.mkdir_p(vgcal_dir, mode: 0o755)
```
が正しい
